### ISSUE TITLE
Container crashes

### ISSUE THREAD

**Issue by rdehuyss** [janjaali/sendGrid-mock#16]
Hi,

we're running this sendgrid-mock in Azure (using 1vCPU and 800MB of memory). We noticed that the container sometimes crashes (when under heavy load - so when a lot of emails are sent).

Did you also already saw this behavior? Is there anything we can do so it doesn't crash?

**Comment by janjaali** [comment]
Hi @rdehuyss, 

No I have not observed such a behavior in the past. This mock was initially "just" created to serve as a mock-endpoint on local developer machines while developing features against sendgrid like API's. It was never intended to be able to handle such loads. 

My first thought would be to add a database to the sendgrid-mock so that not all mails are kept in memory, but I would also assume that such a change would be beyond the initial scope of this mock.

**Comment by rdehuyss** [comment]
Well, were now at 2700 html mails after 10 hours of uptime. All is still well and we're now using 60MB in Azure.

We use it for integration testing.

Let's see if the daily cleanup that I added in the PR helps.

I think we are experiencing crashes when the api returns all the mails. I changed the behavior to only return the last 20 mails.

Cheers!

**Comment by rdehuyss** [comment]
Resolved by making use of mailRetentionDurationInSeconds.
